export enum COMMON_MESSAGE {
    Success = 'Success',
    FinalReportSubmitted = 'Final report submitted successfully. Your case has been closed.',
    Error = 'Something went wrong.',
    Unauthorized = 'Unauthorized access detected.',
    SessionExpired = 'Session expired, please login again.',
    NotFound = '{param} not found.',
    AllDocNotSubmited = '{param} not submitted completely.',
    AlreadyExist = '{param} already exists.',
    InvalidPassword = 'Invalid password.',
    InvalidOtp = 'Invalid Otp.',
    InvalidToken = 'Invalid link.',
    TokenExpired = 'Link expired.',
    PasswordExpired = 'Password expired, please reset it.',
    NotFoundWoParam = 'Not found.',
    TestHasbeenUploaded = 'Test report has been Uploaded.',
    TestHasbeenDeleted = 'Test report has been deleted.',
    DocumentUploadFailed = 'Document upload failed.',
    DocumentUploadSuccess = 'Document uploaded successfully.',
    DocumentDeleted = 'Document deleted successfully.',
    DocumentNotFound = 'Document not found.',
  }